### PLANNING (GBPLANNER) RELATED ###
occupancy_distance_voxelsize_factor: 1.0 #0.5 #ANYmal:1.0 #Flyab:0.5 # must set "occupancy_min_distance_voxel_size_factor" the same

world_frame: world
use_tf_transforms: True
use_freespace_pointcloud: True
tsdf_voxels_per_side: 16 # Size of the block in voxblox
tsdf_voxel_size: 0.2 # 0.2
max_ray_length_m: 20
min_ray_length_m: 0.5
truncation_distance: 0.6
voxel_carving_enabled: True
color_mode: "color"
verbose: False

update_mesh_every_n_sec: 1 # If 0, markers will not be visualized in rviz, but the tsdf will still work

# update_map_every_n_sec: 4.0 # unknown
mesh_min_weight: 1e-4
slice_level: 1.0
method: "fast"
integration_order_mode: "sorted"
max_consecutive_ray_collisions: 0
publish_slices: False
publish_pointclouds: True
allow_clear: True
pointcloud_queue_size: 5
min_time_between_msgs_sec: 0.0
#max_block_distance_from_body: FLT_MAX
publish_tsdf_info: False
publish_traversable: False
traversability_radius: 0.4
enable_icp: False
icp_refine_roll_pitch: False
accumulate_icp_corrections: False # check
timestamp_tolerance_sec: 0.001
publish_tsdf_map: True #False

# ESDF #
esdf_max_distance_m: 3.0
clear_sphere_for_planning: False
clear_sphere_radius: 0.8

# OVERLAP BETWEEN VERSIONS #
use_const_weight: True # check
use_weight_dropoff: True

### NEW SETTINGS FOR BRANCH feature/new_abort_criterion_for_fast_integrator ###
max_weight: 20 #20-200
clearing_ray_weight_factor: 0.1 # From: 0.1 #5 #ANYmal: 0.01 #Flyab: 0.05 #0.05-1.0
#weight_ray_by_range: False
occupancy_min_distance_voxel_size_factor: 1.0