######### OUTPUT FRAME #########
core/msf_output_frame: mimosa_world
######### OUTPUT FRAME #########

core/data_playback: true
core/fixed_bias: 0

#########IMU PARAMETERS#######
core/core_noise_acc: 0.1 # 0.04 #0.02 #0.08 # 0.02 # 0.3 # 0.83
core/core_noise_accbias: 0.008 #0.004 # 0.002 #0.008 # 0.002 # 0.083
core/core_noise_gyr: 0.0013 #0.0013
core/core_noise_gyrbias: 0.00013 #0.00013

pose_sensor/fixed_scale: 1.0
pose_sensor/pose_noise_scale: 0.0
pose_sensor/pose_noise_p_wv: 0.0
pose_sensor/pose_noise_q_wv: 0.0
pose_sensor/pose_noise_q_ic: 0.0
pose_sensor/pose_noise_p_ic: 0.0
pose_sensor/pose_delay: 0.0
# 0.0125 #0.0085 #0.0125 #0.010(vicon) 0.0025(stereo) 0.025(duo) # [s] delay of pose sensor w.r.t. imu
# mixed
# pose_sensor/pose_noise_meas_p: 0.01 #0.085 
# pose_sensor/pose_noise_meas_q: 0.0174
pose_sensor/pose_noise_meas_p: 0.025 #0.085
pose_sensor/pose_noise_meas_q: 0.044

#VICON assumed to be on center of body, TODO: Calculte w.r.t IMU 0, 0.0871557, 0, 0.9961947
pose_sensor/init/p_ic/x: 0.0
pose_sensor/init/p_ic/y: 0.0
pose_sensor/init/p_ic/z: 0.0 #0.0

pose_sensor/init/q_ic/x: 0.0
pose_sensor/init/q_ic/y: 0.0
pose_sensor/init/q_ic/z: 0.0
pose_sensor/init/q_ic/w: 1.0

pose_sensor/pose_fixed_scale: true
pose_sensor/pose_fixed_p_ic: true
pose_sensor/pose_fixed_q_ic: true
pose_sensor/pose_fixed_p_wv: true
pose_sensor/pose_fixed_q_wv: true

pose_sensor/pose_absolute_measurements: true
pose_sensor/pose_use_fixed_covariance: true
pose_sensor/pose_measurement_world_sensor: true  # selects if sensor measures its position w.r.t. world (true, e.g. Vicon) or the position of the world coordinate system w.r.t. the sensor (false, e.g. ethzasl_ptam
pose_sensor/pose_sensor/pose_measurement_minimum_dt: 0.005 # Sets the minimum time in seconds between two pose measurements.

/msf/filter_window: 8
# core/vn100_px4_tf/translation: [-0.03705, 0.01878, 0.0104]
# core/vn100_px4_tf/rotation: [0.0, 0.0, 0.0, 1.0]
core/vn100_px4_tf/translation: [-0.0, -0.01878, -0.030]
core/vn100_px4_tf/rotation: [0.0, 0.0, 0.0, 1.0]
