subscribers:
  input:
    topic:            /freezable_laser_map
    queue_size:       1

publishers:
  output:
    topic:            /laser_map_on_demand_loam_frame
    queue_size:       1
    latch:            false

servers:
  publish_next_incoming_message:
    service: publish_next_laser_map
