composite_cbf:
    ros__parameters:
        epsilon: 0.25
        pole_0: -2.5
        kappa: 80.0
        gamma: 40.0
        alpha: 1.5
        lp_gain_in: 0.4
        lp_gain_out: 0.2
        max_acc_xy: 3.0
        max_acc_z: 3.0
        output_frame_viz: rmf/base_link
        ctrl_freq: 50.0
        obs_to: 1.0  # obstacle timeout [sec]
        cmd_to: 1.0  # command timeout [sec]
