  # Configurations for the exploration pipeline.
  # For more details, please check comments in the params.h file and the wiki.
  #-------------------------------------------------------------------------------
  # ROBOT CONFIGURATION
  #-------------------------------------------------------------------------------
RobotParams:
  type:               kAerialRobot
  size:               [0.8, 0.8, 0.7] # Actual size of the robot in meters [x, y, z]
  size_extension_min: [0.1, 0.1, 0.1] # minimum extension outside of robot size allowed to operate
  size_extension:     [0.2, 0.2, 0.3] # maximum extension outside of the robot size
  center_offset:      [0.0, 0.0, 0.0]
  relax_ratio:        0.5 # Used to define an intermediate size between size_extension_min and size_extension for planning
  bound_mode:         kExtendedBound
  safety_extension:   [1.0, 1.0, 1.0] # Safety extension outside the bounding box of a path segment used to improve it by pushing it away from obstacles
#-------------------------------------------------------------------------------
# SENSOR CONFIGURATION
#  sensor_list: Define a set of sensors relevant to the exploration task.
#  rotations: ZYX order;
#             all follows ROS convention (X-forward, Y-left, Z-Up).
#-------------------------------------------------------------------------------
SensorParams:
  sensor_list:      ["OS064", "Cam"]
  OS064:
    type:           kLidar
    max_range:      20
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [rad(pi), 0.0, 0.0]
    fov:            [rad(pi), rad(0.7*pi)]
    resolution:     [rad(7.5*pi/180), rad(7.5*pi/180)]
    frontier_percentage_threshold: 0.01
  Cam:
    type:           kLidar
    max_range:      2.5
    min_range:      0.0
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.26, 0.0]
    fov:            [rad(100*pi/180.0), rad(80*pi/180.0)]
    # resolution:     [rad(5.0*pi/180), rad(5.0*pi/180)]
    # resolution:     [rad(2.0*pi/180), rad(2.0*pi/180)]
    resolution:     [0.06, 0.06]  # 0.2/3.0 (voxel_res / max_range)
    frontier_percentage_threshold: 0.06

CameraAnnotationParams:  # Annotate voxels seen by this camera model during the mission
  sensor_list:      ["Cam"]
  Cam:
    type:           kLidar
    # rot_lims:       [-1.57, 1.57]
    rot_lims:       [-1.55, 1.55]
    max_range:      2.0 #2.5
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.26, 0.0]
    fov:            [rad(84*pi/180.0), rad(64*pi/180.0)]
    resolution:     [rad(1.0*pi/180), rad(1.0*pi/180)]
    frontier_percentage_threshold: 0.01
#-------------------------------------------------------------------------------
# SAMPLING SPACE CONFIGURATION
#   Global: Strictly defined bounds for the whole environment.
#   Local: Define a local space wrt current robot state for planning.
#-------------------------------------------------------------------------------
BoundedSpaceParams:
  Global:
    type:           kCuboid
    # RL
    # min_val:        [-1.0, -300.0, -10.0]
    # max_val:        [32.0, 300.0, 2.0]
    min_val:        [-1.0, -300.0, -2.0]
    max_val:        [32.0, 2.0, 1.75]
    # min_val:        [-0.5, -2.5, -0.2]
    # max_val:        [4.0, 1.2, 2.0]
    # Room
    # min_val:        [-1.5, -300.2, -10.2]
    # max_val:        [300.0, 300.2, 3.05]
    # Tunnel
    # min_val:        [-36.0, -3.0, -10.2]
    # max_val:        [30.0, 30.2, 3.05]
    # Basement
    # min_val:        [-3.0, -10.2, -0.2]
    # max_val:        [50.5, 10.2, 2.25]
    # min_val:        [-0.0, -2.8, -0.2]
    # max_val:        [15.5, 2.8, 2.0]
    # min_val:        [-1.0, -2.0, -0.2]
    # max_val:        [500.5, 2.0, 1.75]
    # For arena:
    # min_val:        [-3.2, -2.0, 0.0]
    # max_val:        [3.0, 3.7, 1.8]
  Local:
    type:           kCuboid
    # min_val:        [-15.0, -15.0, -3.0]
    # max_val:        [15.0, 15.0, 3.0]
    # min_val:        [-4.0, -4.0, -4.0]
    # max_val:        [4.0, 4.0, 4.0]
    min_val:        [-15.0, -15.0, -2.0]
    max_val:        [15.0, 15.0, 2.0]
    min_extension:  [-20.0, -20.0, -20.0]
    max_extension:  [20.0, 20.0, 20.0]
  LocalSearch:
    type:           kCuboid
    min_val:        [-15.0, -15.0, -6.0]
    max_val:        [15.0, 15.0, 6.0]
  # Adaptive OBB:
  LocalAdaptiveExp:
    type:           kCuboid
    min_val:        [-10.0, -10.0, -0.75]
    max_val:        [10.0, 10.0, 0.75]
NoGainZones:
  g1:  # Back
    type:           kCuboid
    min_val:        [-50.0, -10.0, -10.0]
    max_val:        [2.0, 10.0, 10.0]
#-------------------------------------------------------------------------------
# SAMPLING POLICY CONFIGURATION
#   Sample space limited to 4 states: X, Y, Z, and Heading
#-------------------------------------------------------------------------------
RandomSamplerParams:
  SamplerForExploration:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      # pdf_type:       kUniform
      # sample_mode:    kManual
      # min_val:        rad(-pi/2)
      # max_val:        rad(pi/2)
      pdf_type:       kConst
      sample_mode:    kManual
      const_val:      0.0
  SamplerForSearching:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      # pdf_type:       kUniform
      # sample_mode:    kManual
      # min_val:        rad(-pi/2)
      # max_val:        rad(pi/2)
      pdf_type:       kConst
      sample_mode:    kManual
      const_val:      0.0
  SamplerForAdaptiveExp:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      # pdf_type:       kUniform
      # sample_mode:    kManual
      # min_val:        rad(-pi/2)
      # max_val:        rad(pi/2)
      pdf_type:       kConst
      sample_mode:    kManual
      const_val:      0.0

#-------------------------------------------------------------------------------
# EXPLORATION CONFIGURATION
# exp_sensor_list: sensors used to compute exploration gain.
#-------------------------------------------------------------------------------
PlanningParams:
  type:             kBasicExploration #kAdaptiveExploration, kBasicExploration
  rr_mode:          kGraph
  exp_sensor_list:  ["OS064"]
  inspection_sensor_list:  ["Cam"]
  # exp_sensor_list:  ["Cam"]
  # no_gain_zones_list: ["g1"]
  v_max:            1.0 # max velocity m/s
  v_homing_max:     0.9 # max velocity m/s
  yaw_rate_max:     0.2 # max angular velocity rad/s
  yaw_tangent_correction: false # If true - all headings will be along the path segment
  edge_length_min:  0.2
  edge_length_max:  3.0
  edge_overshoot:   0.0 # m - Account for possible tracking error by collision checking on an extended edge
  num_vertices_max: 400 # 400 # graph building stops if these many vertices are added 
  num_edges_max:    7000 # graph building stops if these many edges are added
  num_loops_cutoff: 2000 # Maximum iterations in which no vertices or edges are added to the graph
  num_loops_max:    3000 # Maximum iterations possible for graph building
  nearest_range:    3.0 # The max range within which a new vertex can be connected to an existing vertex
  nearest_range_min: 0.2 # >= edge_length_min
  nearest_range_max: 3.0 # <= edge_length_max
  use_current_state: true # If true, it will use the current state to plan from instead of the state provided by the PCI in the service call
  use_ray_model_for_volumetric_gain: true # if false, will check voxel by voxel in the sensor frustum 
  exp_gain_voxel_size: 0.8 # used if use_ray_model_for_volumetric_gain is false
  # Gains:
  path_length_penalty: 0.02 # 0.4
  path_direction_penalty: 0.03 # 0.01
  occupied_voxel_gain: 0.0
  free_voxel_gain:  1.0 # prefer directions towards more free voxels in case of the dead-end
  unknown_voxel_gain: 60.0

  traverse_length_max: 10.0 # Maximum length of the best path will be truncated to for actual traversal
  traverse_time_max: 500.0
  path_safety_enhance_enable: false  # Disable for ballast small, non corridor like environments
  augment_free_voxels_time: 3
  free_frustum_before_planning: false
  freespace_cloud_enable: false
  leafs_only_for_volumetric_gain: true # Whether to calculate gain of the entire path or only the leaf nodes
  cluster_vertices_for_gain: false
  clustering_radius: 0.5
  path_interpolation_distance: -0.5 # -1.0

  active_homing_update_radius: 10.0
  local_navigation_reaching_radius: 2.0

  planning_backward: true

  use_gvi: false
  
  time_budget_limit: 200 # seconds
  auto_homing_enable: true
  go_home_if_fully_explored: true
  auto_global_planner_enable: true

  nonuniform_ray_cast: false
  ray_cast_step_size_multiplier: 1.0
  max_low_gain_iters: 3

  use_camera_gain: false
  annotate_map_with_camera: false

  inspection_planning: false
  basic_inspection_viewpoints: true

  keep_leaf_yaw_only: true # true -> for leaves gain

  box_check_method: 0
  line_check_method: 1

  add_only_frontiers_to_global_graph: false

  # small comp
  min_coverage_percentage: 0.9
  inspection_xy_spacing: 1.0 # 1.5
  inspection_z_spacing: 0.6 #0.6 # 1.0 # 2.0
  inspection_thr_esdf_dist: 0.5
  inspection_target_viewing_range: 1.5 # 2.5
  inspection_pt_dist: 0.9 # 1.0
  verification_target_viewing_range: 2.5
  inspection_graph_vertices: 250
  max_inspection_vertices: 50
  num_lkh_iterations: 10

  enable_manhole_traversal: false
  manhole_alignment_z_offset: 0.0 # -0.12 # -0.25
  only_manhole_traversal: false  # If enabled: It uses the global bounding box!!!! To be used to testing manhole
  manhole_traversal_path_edge_length: 1.25

  use_flipped_yaw: true

  auto_manhole_path_approval: true
  max_manhole_height: 2.0  # With respect to world (NOT compartment floor)

  # Demo
  max_exploration_iterations: 200
  exploration_only: true
  # Setting centers and compartment dimensions
  compartment_centers: [0.0, 0.0, 0.0] # 1.1
  compartment_dimensions:
    type:           kCuboid
    # min_val:        [-2.0, -3.0, -1.1]
    # max_val:        [2.0, 3.0, 1.1]
    min_val:        [-5.0, -1.5, 0.5] # 1.6
    max_val:        [10.0, 10.5, 2.5]

  geofence_checking_enable: true

AdaptiveObbParams:
  type: kPca
  local_pointcloud_range: 50.0
  bounding_box_size_max: 35

GeofenceParams:
  AreaList: ["GBack"]
  GBack:
    center: [-2, 0.0, 0.0]
    size:   [2.0, 4.0, 0.0]
  G2:
    center: [-3.128, -0.937, 0.0]
    size:   [2.0, 2.0, 0.0]
